/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.github.venyunoc.badgepic;

import com.github.venyunoc.badgepic.services.BioDataService;
import com.github.venyunoc.badgepic.services.ImageDataService;
import com.github.venyunoc.badgepic.services.ImageWriterService;
import java.awt.image.BufferedImage;
import javax.swing.ImageIcon;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *
 * @author nathan
 */
public class GUI extends javax.swing.JFrame {

    private final ImageDataService imageDataService;
    private final ImageWriterService imageWriterService;
    private final BioDataService bioDataService;
    
    private BufferedImage image;

    /**
     * Creates new form CombinedGuI
     */
    public GUI(ImageDataService imageDataService, ImageWriterService imageWriterService, BioDataService bioDataService) {
        this.imageDataService = imageDataService;
        this.imageWriterService = imageWriterService;
        this.bioDataService = bioDataService;
        
        this.image = new BufferedImage(640, 480, BufferedImage.TYPE_INT_RGB);

        initComponents();

        DocumentListener dl = new TextFieldDocumentListener();

        this.firstNameInput.getDocument().putProperty("id", 1);
        this.lastNameInput.getDocument().putProperty("id", 2);
        this.badgeNumberInput.getDocument().putProperty("id", 3);

        this.firstNameInput.getDocument().addDocumentListener(dl);
        this.lastNameInput.getDocument().addDocumentListener(dl);
        this.badgeNumberInput.getDocument().addDocumentListener(dl);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bioDataPanel = new javax.swing.JPanel();
        lblFirstName = new javax.swing.JLabel();
        firstNameInput = new javax.swing.JTextField();
        lblLastName = new javax.swing.JLabel();
        lastNameInput = new javax.swing.JTextField();
        lblBadgeNumber = new javax.swing.JLabel();
        badgeNumberInput = new javax.swing.JTextField();
        imagePreviewPanel = new javax.swing.JPanel();
        captureButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        gutter = new javax.swing.JLabel();
        imgLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bioDataPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Personal Information"));

        lblFirstName.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblFirstName.setText("First Name");

        firstNameInput.setNextFocusableComponent(lastNameInput);

        lblLastName.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblLastName.setText("Last Name");

        lastNameInput.setNextFocusableComponent(badgeNumberInput);

        lblBadgeNumber.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblBadgeNumber.setText("Badge Number");

        badgeNumberInput.setNextFocusableComponent(captureButton);

        javax.swing.GroupLayout bioDataPanelLayout = new javax.swing.GroupLayout(bioDataPanel);
        bioDataPanel.setLayout(bioDataPanelLayout);
        bioDataPanelLayout.setHorizontalGroup(
            bioDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bioDataPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bioDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBadgeNumber)
                    .addComponent(lblLastName, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblFirstName, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bioDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(firstNameInput)
                    .addComponent(lastNameInput)
                    .addComponent(badgeNumberInput))
                .addContainerGap())
        );
        bioDataPanelLayout.setVerticalGroup(
            bioDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bioDataPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bioDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFirstName)
                    .addComponent(firstNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(bioDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLastName)
                    .addComponent(lastNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(bioDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBadgeNumber)
                    .addComponent(badgeNumberInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        imagePreviewPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Image Preview"));

        captureButton.setText("Capture Image");
        captureButton.setNextFocusableComponent(saveButton);
        captureButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                captureButtonActionPerformed(evt);
            }
        });

        saveButton.setText("Save Image");
        saveButton.setNextFocusableComponent(firstNameInput);
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        gutter.setText("Output file path: ");

        imgLabel.setPreferredSize(new java.awt.Dimension(640, 480));

        javax.swing.GroupLayout imagePreviewPanelLayout = new javax.swing.GroupLayout(imagePreviewPanel);
        imagePreviewPanel.setLayout(imagePreviewPanelLayout);
        imagePreviewPanelLayout.setHorizontalGroup(
            imagePreviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(imagePreviewPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(imagePreviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imgLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(gutter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(imagePreviewPanelLayout.createSequentialGroup()
                        .addComponent(captureButton, javax.swing.GroupLayout.DEFAULT_SIZE, 435, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(saveButton, javax.swing.GroupLayout.DEFAULT_SIZE, 435, Short.MAX_VALUE)))
                .addContainerGap())
        );
        imagePreviewPanelLayout.setVerticalGroup(
            imagePreviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, imagePreviewPanelLayout.createSequentialGroup()
                .addComponent(imgLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(imagePreviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(captureButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gutter))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bioDataPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(imagePreviewPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 910, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bioDataPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(imagePreviewPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 627, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public class TextFieldDocumentListener implements DocumentListener {

        @Override
        public void insertUpdate(DocumentEvent e) {
            this.onChange(e);
        }

        @Override
        public void removeUpdate(DocumentEvent e) {
            this.onChange(e);
        }

        @Override
        public void changedUpdate(DocumentEvent e) {
            return;
        }

        private void onChange(DocumentEvent e) {
            int id = (int) e.getDocument().getProperty("id");
            switch (id) {
                case 1:
                    bioDataService.submitFirstName(firstNameInput.getText());
                    break;
                case 2:
                    bioDataService.submitLastName(lastNameInput.getText());
                    break;
                case 3:
                    bioDataService.submitBadgeNumber(badgeNumberInput.getText());
                    break;
                default:
                    break;
            }
            updateGutter();
        }
    }
    
    private void updateGutter() {
        String filename = String.format("%s - %s, %s.jpg", 
                                            this.bioDataService.badgeNumber(),
                                            this.bioDataService.lastName(),
                                            this.bioDataService.firstName());
        String fullPath = this.imageWriterService.folder.resolve(filename).toString();
        
        this.gutter.setText(String.format("Output file path: %s", fullPath));
    }

    private void captureButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_captureButtonActionPerformed
        this.image = this.imageDataService.getImageData();
        this.imgLabel.setIcon(new ImageIcon(image));
    }//GEN-LAST:event_captureButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        if (this.image.getWidth() > 0 && this.image.getHeight() > 0) {
            this.imageWriterService.writeImage(
                    String.format("%s - %s, %s.jpg",
                            this.bioDataService.badgeNumber(),
                            this.bioDataService.lastName(),
                            this.bioDataService.firstName()), image);
        }
    }//GEN-LAST:event_saveButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField badgeNumberInput;
    private javax.swing.JPanel bioDataPanel;
    private javax.swing.JButton captureButton;
    private javax.swing.JTextField firstNameInput;
    private javax.swing.JLabel gutter;
    private javax.swing.JPanel imagePreviewPanel;
    private javax.swing.JLabel imgLabel;
    private javax.swing.JTextField lastNameInput;
    private javax.swing.JLabel lblBadgeNumber;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables
}
